name: Build EXE with PyInstaller

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build with PyInstaller
      run: pyinstaller --noconfirm --onefile --windowed vector_calculator_gui_with_angle.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: vector_calculadora
        path: dist/*.exe
